services:

  mysql:
    image: mysql:8.0
    container_name: mysql
#    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@01
      MYSQL_DATABASE: guessword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  guessword-api:
    build: .
    container_name: wordle-api
    ports:
      - "8080:8080"
    depends_on:
       mysql:
         condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/guessword
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mysql@01
volumes:
  db_data:
